services:
  btc-staker:
    container_name: btc-staker
    # https://github.com/babylonlabs-io/btc-staker/commit/484bcb8fd9b7b0b525234d704dd049b1ef18e29f
    # euphrates-0.5.0-rc.0
    image: babylonlabs/btc-staker:484bcb8fd9b7b0b525234d704dd049b1ef18e29f
    env_file:
      - "${PWD}/.env.babylon-integration"
    volumes:
      - ${PWD}/.btc-staker:/home/btcstaker/.stakerd
    ports:
      - "15812:15812"
    restart: unless-stopped
    networks:
      - babylon-integration

  consumer-eotsmanager:
    container_name: consumer-eotsmanager
    # https://github.com/babylonlabs-io/finality-provider/commit/45a24e1f5c235a829eaeca3c3336053032ec0088
    image: babylonlabs/finality-provider:45a24e1f5c235a829eaeca3c3336053032ec0088
    command: eotsd start
    volumes:
      - ${PWD}/.consumer-eotsmanager:/home/finality-provider/.eotsd
    ports:
      - "15813:15813"
    restart: unless-stopped
    networks:
      - babylon-integration

  consumer-finality-provider:
    container_name: consumer-finality-provider
    # https://github.com/babylonlabs-io/finality-provider/commit/45a24e1f5c235a829eaeca3c3336053032ec0088
    image: babylonlabs/finality-provider:45a24e1f5c235a829eaeca3c3336053032ec0088
    command: fpd start
    volumes:
      - ${PWD}/.consumer-finality-provider:/home/finality-provider/.fpd
    ports:
      - "12581:12581"
    depends_on:
      - consumer-eotsmanager
    restart: unless-stopped
    networks:
      - babylon-integration

networks:
  babylon-integration: